package GUI;

import javax.swing.*;
import java.awt.*;

public class LoginGUI {
    private JPanel loginPageBackground;
    private JPanel leftLabels;
    private JPanel bottomButtons;
    private JPanel rightTextField;
    private JPanel topTitle;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JLabel titleLabel;
    private JTextField usernameField;
    private JTextField passwordField;
    private JButton signInButton;
    private JButton registerButton;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        loginPageBackground.setLayout(new BorderLayout(0, 0));
        loginPageBackground.setBackground(new Color(-11038572));
        leftLabels = new JPanel();
        leftLabels.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        leftLabels.setBackground(new Color(-11038572));
        loginPageBackground.add(leftLabels, BorderLayout.WEST);
        usernameLabel = new JLabel();
        usernameLabel.setForeground(new Color(-16579837));
        usernameLabel.setText("Username");
        leftLabels.add(usernameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setForeground(new Color(-16579837));
        passwordLabel.setText("Password");
        leftLabels.add(passwordLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rightTextField = new JPanel();
        rightTextField.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        rightTextField.setBackground(new Color(-11038572));
        loginPageBackground.add(rightTextField, BorderLayout.EAST);
        usernameField = new JTextField();
        usernameField.setBackground(new Color(-1));
        rightTextField.add(usernameField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField = new JTextField();
        passwordField.setBackground(new Color(-1114881));
        rightTextField.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        bottomButtons = new JPanel();
        bottomButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bottomButtons.setBackground(new Color(-11038572));
        loginPageBackground.add(bottomButtons, BorderLayout.SOUTH);
        signInButton = new JButton();
        signInButton.setText("Sign In");
        bottomButtons.add(signInButton);
        registerButton = new JButton();
        registerButton.setText("Register");
        bottomButtons.add(registerButton);
        topTitle = new JPanel();
        topTitle.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        topTitle.setBackground(new Color(-11038572));
        topTitle.setEnabled(false);
        loginPageBackground.add(topTitle, BorderLayout.NORTH);
        titleLabel = new JLabel();
        titleLabel.setBackground(new Color(-11038572));
        Font titleLabelFont = this.$$$getFont$$$("Bradley Hand ITC", Font.BOLD, 24, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setForeground(new Color(-16579837));
        titleLabel.setText("Property Renting Application");
        topTitle.add(titleLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPageBackground;
    }
}
