package GUI;

import Server.Address;
import Server.Criteria;
import Server.Property;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

public class ViewProperties {
    private JPanel panel1;
    private JPanel titlePanel;
    private JPanel buttonPanel;
    private JButton criteriaCreateButton;
    private JButton backButton;
    private JButton emailButton;
    private JList displayList;
    private JFrame frame;
    private CriteriaGUI criteriaGUI;

    ArrayList<Property> properties;
    private PrintWriter outBuffer;
    private BufferedReader inBuffer;

    public ViewProperties(PrintWriter outBuffer, BufferedReader inBuffer) {
        frame = new JFrame("Manger");
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        backButton.addActionListener(new ALBack());
        emailButton.addActionListener(new ALEmail());
        criteriaCreateButton.addActionListener(new ALCreateCriteria());
        properties = new ArrayList<>();
        this.outBuffer = outBuffer;
        this.inBuffer = inBuffer;

        //Fill in data


        frame.setVisible(true);
    }

    private class ALBack implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            frame.dispose();
        }
    }

    private class ALEmail implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            int slectedIndex = displayList.getSelectedIndex();
            int propID = -1;
            if (slectedIndex >= 0) {
                propID = properties.get(slectedIndex).getListID();
            }
            //TODO work with the client
            if (propID < 0) {
                System.out.println("Email to " + propID);
            }
        }
    }

    private class ALCreateCriteria implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            criteriaGUI = new CriteriaGUI(new ALRegCritera());

        }
    }

    private class ALRegCritera implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent actionEvent) {
            Criteria criteria = criteriaGUI.pullCriteria();

            outBuffer.println(criteria.toServerString());
            String[] parts = new String[0];
            try {
                parts = Client.readServer(inBuffer).split("#");
            } catch (IOException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            Property properties[] = new Property[parts.length];
            for (int i = 0; i < parts.length; i++) {
                properties[i] = new Property(parts[i]);
            }
            panel1.remove(displayList);
            displayList = new JList(properties);
            panel1.add(displayList);

        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        titlePanel = new JPanel();
        titlePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        titlePanel.setBackground(new Color(-11038572));
        panel1.add(titlePanel, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Bradley Hand ITC", Font.BOLD, 24, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16579837));
        label1.setText("Registered Properties");
        titlePanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        buttonPanel.setBackground(new Color(-11038572));
        panel1.add(buttonPanel, BorderLayout.SOUTH);
        emailButton = new JButton();
        emailButton.setText("Email");
        buttonPanel.add(emailButton);
        criteriaCreateButton = new JButton();
        criteriaCreateButton.setText("criteriaCreate");
        buttonPanel.add(criteriaCreateButton);
        backButton = new JButton();
        backButton.setText("Back");
        buttonPanel.add(backButton);
        displayList = new JList();
        panel1.add(displayList, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
